kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/nfs
parameters:
  type: nfs
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate
